#!/bin/sh
# Creates an "Install Debian" icon on the live session tested with:
# Xfce, LXDE, LXqt, Gnome, KDE, Mate, Cinnamon


# Create ~/Desktop just in case this runs before the xdg folder
# creation script.
mkdir -p ~/Escritorio
cp /usr/share/applications/install-huayra.desktop ~/Escritorio
# Xfce needs this executable otherwise it complains, everything
# else doesn't seem to care either way.
chmod +x ~/Escritorio/install-huayra.desktop
